language: node_js
node_js:
  - "5.7"
  - "5.6"
  - "4.3"
  - "0.12"
  - "0.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-software-properties -qq
  - sudo add-apt-repository ppa:ondrej/php5-5.6 -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5
email:
  on_success: never
